INSERT INTO role(role) VALUES('SCIENTIST');
INSERT INTO role(role) VALUES('PARTICIPANT');
INSERT INTO role(role) VALUES('REVIEWER');
INSERT INTO role(role) VALUES('ORGANIZER');

INSERT INTO status VALUES(1,'PENDING');
INSERT INTO status VALUES(2,'ACCEPTED');
INSERT INTO status VALUES(3,'REJECTED');
